name: Update container image

on:
  schedule:
    # At minute 13 past every 6th hour. This is 45 minutes before the servers
    # watchtower triggers.
    - cron: "13 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get base image
        run: awk '/^FROM / {print "BASEIMAGE=" $2}' containers/Dockerfile >>"$GITHUB_ENV"
        if: ${{ github.event_name == 'schedule' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if baseimage update is available
        id: check
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: ${{ env.BASEIMAGE }}
          image: kgraefe/brscan-multipage:latest
        if: ${{ github.event_name == 'schedule' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          push: true
          tags: kgraefe/brscan-multipage:latest
          build-contexts: |
            projectroot=.
        if: ${{ github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true' }}
